config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
    }
  
  root 'home#top'
  get 'home/about', to: 'home#about'
  resources :books, only: [:index,:show,:edit,:update,:create,:destroy]
  resources :users, only: [:index,:show,:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  
  def after_sign_in_path_for(resource) 
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  def current_user?(user)
    user == current_user
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit,:update]
  
  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find_by(id: @book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to "/books/#{@book.id}"
    else
      render 'edit'
    end
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to "/books/#{ @book.id }"
    else
      @books = Book.all
      render 'index'
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to "/books"
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title,:body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = User.find_by(id: @book.user_id)
    redirect_to "/books" unless @user == current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:introduction,%i(profile_image)])
  end
  
  def update_resource(resource,params)
    resource.update_without_password(params)
  end
  
  def after_update_path_for(_resource)
    user_path(current_user.id)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit]
  
  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  private
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      
      <%= render 'shared/error_messages', collection: @book %>
      
      <%= form_with model: @book, url: book_path, method: :patch do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title "%>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :body, "Opinion"%>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
      <% end %>
      <a href="/books/<%= @book.id %>">Show</a>
       | 
      <a href="/books">Back</a>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  
  <%= render 'shared/error_messages', collection: @book %>
  
  <div class="row">
    
      <%= render 'shared/info', user: current_user, book: @book %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-invers">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <a href="/users/<%= book.user.id %>">
                  <%= image_tag book.user.get_profile_image(80,80) %>
                </a>
              </td>
              <td>
                <%= link_to book.title, "/books/#{book.id}" %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    
    <%= render 'shared/info', user: @user, book: @book%>
    
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-invers">
        <tbody>
            <tr>
              <td>
                <a href="/users/<%= @book.user.id %>">
                  <%= image_tag @book.user.get_profile_image(80,80) %>
                <br>
                <%=  @book.user.name %>
                </a>
              </td>
              <td>
                <a href="/books/<%= @book.id %>"><%= @book.title %></a>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <% if @book.user == current_user %>
              <td>
                <a href="/books/<%= @book.id %>/edit" class="btn btn-sm btn-success">Edit</a>
              </td>
              <td>
                <a href="/books/<%= @book.id %>" class="btn btn-sm btn-danger" rel="nofollow" data-method="delete" data-confirm="本当に削除しますか？">Destroy</a>
              </td>
              <% end %>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="mx-auto px-">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>IN <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookerz2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo links-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <haeder>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="botton" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expand="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <a class="nav-link text-light" href="/users/<%= current_user.id %>"><i class="fas fa-home"></i> Home </a>
              </li>
              <li>
                <a class="nav-link text-light" href="/users"><i class="fas fa-users"></i> Users </a>
              </li>
              <li>
                <a class="nav-link text-light" href="/books"><i class="fas fa-book-open"></i> Books </a>
              </li>
              <li>
                <a class="nav-link text-light" href="/users/sign_out" rel="nofollow" data-method="delete"><i class="fas fa-sign-out-alt"></i> Log out </a>
              </li>
              <% else %>
              <li>
                <a class="nav-link text-light" href="/"><i class="fas fa-home"></i> Home </a>
              </li>
              <li>
                <a class="nav-link text-light" href="/home/about"><i class="fas fa-link"></i> About </a>
              </li>
              <li>
                <a class="nav-link text-light" href="/users/sign_up"><i class="fas fa-user-plus"></i> Sign up </a>
              </li>
              <li>
                <a class="nav-link text-light" href="/users/sign_in"><i class="fas fa-sign-in-alt"></i> Log in </a>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </haeder>
    <main>
      <p id=notice><%= notice %></p>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
    
  </body>
</html>

app/views/shared/_error_messages.html.erb
<div id="error_explanation">
    <% if collection.errors.any? %>
    <h3><%= pluralize(collection.errors.count, "error")%> prohibited this obj from being saved:</h3>
    <ul>
      <% collection.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
      <% end %>
    </ul>
    <% end %>
  </div>

app/views/shared/_info.html.erb
<div class="col-md-3">
        <h2>User info</h2>
          <%= image_tag user.get_profile_image(100,100) %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
          </tbody>
        </table>
        
        <div class="row">
          <a href="/users/<%= user.id %>/edit" class="btn btn-outline-secondary btn-block"><i class="fas fa-user-cog"></i></a>
        </div>
        
        <h2 class="mt-3">New book</h2>
        
        <%= form_with model: book, url: books_path, method: :post do |f| %>
        
        <div class="form-group">
          <%= f.label :title, "Title" %>
          <%= f.text_field :title, class: "form-control", value: "" %>
        </div>
        <div class="form-group">
          <%= f.label :body, "Opinion" %>
          <%= f.text_area :body, class: "form-control", value: "" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Book", class: "btn btn-success"  %>
        </div>
        
        <% end %>
    </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>User info</h1>
      <%= form_with model: @user, url: user_registration_path, method: :patch do |f| %>
      
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :profile_image %>
        <%= f.file_field :profile_image, class: "form-control-file", accept: "image/*" %>
      </div>
      
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      </div>
      
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    
    <%= render 'shared/info', user: current_user, book: @book %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-invers">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= image_tag user.get_profile_image(80,80) %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <a href="/users/<%= user.id %>">Show</a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'shared/info', user: @user, book: @book%>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-invers">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <a href="/users/<%= book.user.id %>">
                  <%= image_tag book.user.get_profile_image(80,80) %>
                </a>
              </td>
              <td>
                <a href="/books/<%= book.id %>"><%= book.title %></a>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>